#!/usr/bin/sh

echo "Linux 5.1.5-arch1-2-ARCH (vcaprarola) 	06/08/2019 	_x86_64_	(8 CPU)"
echo ""
echo "11:01:52 AM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle"
echo "11:01:53 AM  all    8.82    0.00    3.27    0.00    0.25    0.00    0.00    0.00    0.00   87.66"
echo "Average:     all    8.82    0.00    3.27    0.00    0.25    0.00    0.00    0.00    0.00   87.66"
